### ISSUE TITLE
NPM install failed with VS2013, 2015

### ISSUE THREAD

**Issue by vasumahesh1** [tojocky/node-pdfium-native#10]
Hi,

I tried to install pdfium with VS2015 which eventually failed. But then I read in another (issue)[] where you were having a successful build with VS2013. I did the same but got the following error:

```
..\src\node_pdfium.cc(507): error C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument t
ypes [P:\titan-pos\node_modules\pdfium\build\node_pdfium.vcxproj]
          C:\Users\Vasu\.node-gyp\4.2.6\include\node\node_buffer.h(43): could be 'v8::MaybeLocal<v8::Object> node::Buff
  er::New(v8::Isolate *,char *,size_t)'
          C:\Users\Vasu\.node-gyp\4.2.6\include\node\node_buffer.h(31): or       'v8::MaybeLocal<v8::Object> node::Buff
  er::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, unsigned __int64)'
..\src\node_pdfium.cc(578): error C2039: 'HasIndexedPropertiesInExternalArrayData' : is not a member of 'v8::Object' [P
:\titan-pos\node_modules\pdfium\build\node_pdfium.vcxproj]
          c:\users\vasu\.node-gyp\4.2.6\include\node\v8.h(2587) : see declaration of 'v8::Object'
..\src\node_pdfium.cc(580): error C2039: 'GetIndexedPropertiesExternalArrayData' : is not a member of 'v8::Object' [P:\
titan-pos\node_modules\pdfium\build\node_pdfium.vcxproj]
          c:\users\vasu\.node-gyp\4.2.6\include\node\v8.h(2587) : see declaration of 'v8::Object'
..\src\node_pdfium.cc(581): error C2039: 'GetIndexedPropertiesExternalArrayDataLength' : is not a member of 'v8::Object
' [P:\titan-pos\node_modules\pdfium\build\node_pdfium.vcxproj]
          c:\users\vasu\.node-gyp\4.2.6\include\node\v8.h(2587) : see declaration of 'v8::Object'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
70:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd P:\titan-pos\node_modules\pdfium
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "pdfium" "--msvs_version=2013"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! pdfium@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdfium@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pdfium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdfium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     P:\titan-pos\npm-debug.log
```

Is there an Issue with Node version? I am currently on 4.2.6. Gonna try to downgrade to 0.12.10 maybe and give it a shot.

**Comment by vasumahesh1** [comment]
Issue fixed by downgrading to 0.12.10 (x64) the x32 bit threw a node-gyp error. 64bit works just fine. 

Can npm install now :). Closing the Issue.

**Comment by rschaar** [comment]
win_delay_load_hook.cc

..\src\node_pdfium.cc(507): error C2665: "node::Buffer::New": Durch keine der 4 Überladungen konnten alle Argumenttypen konvertiert werden. [C:\Users\rschaar\Documents\Visual Studio 2015\Projects\PdfMakeJS\sr
c\PdfMakeJS\node_modules\pdfium\build\node_pdfium.vcxproj]
  C:\Users\rschaar.node-gyp\4.4.7\include\node\node_buffer.h(43): note: kann "v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate *,char *,std::size_t)" sein (Quelldatei wird kompiliert ..\src\node_pdfi
  um.cc)
  C:\Users\rschaar.node-gyp\4.4.7\include\node\node_buffer.h(31): note: oder "v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate *,v8::Localv8::String,node::encoding)" (Quelldatei wird kompiliert ..\
  src\node_pdfium.cc)
  ..\src\node_pdfium.cc(507): note: bei Anpassung der Argumentliste "(v8::Isolate *, const char *, unsigned __int64)"
..\src\node_pdfium.cc(540): warning C4996: 'node::FatalException': wurde als veraltet deklariert [C:\Users\rschaar\Documents\Visual Studio 2015\Projects\PdfMakeJS\src\PdfMakeJS\node_modules\pdfium\build\node_
pdfium.vcxproj]
  C:\Users\rschaar.node-gyp\4.4.7\include\node\node.h(282): note: Siehe Deklaration von "node::FatalException"
..\src\node_pdfium.cc(578): error C2039: "HasIndexedPropertiesInExternalArrayData": Ist kein Element von "v8::Object" [C:\Users\rschaar\Documents\Visual Studio 2015\Projects\PdfMakeJS\src\PdfMakeJS\node_modul
es\pdfium\build\node_pdfium.vcxproj]
  c:\users\rschaar.node-gyp\4.4.7\include\node\v8.h(2587): note: Siehe Deklaration von "v8::Object"
..\src\node_pdfium.cc(580): error C2039: "GetIndexedPropertiesExternalArrayData": Ist kein Element von "v8::Object" [C:\Users\rschaar\Documents\Visual Studio 2015\Projects\PdfMakeJS\src\PdfMakeJS\node_modules
\pdfium\build\node_pdfium.vcxproj]
  c:\users\rschaar.node-gyp\4.4.7\include\node\v8.h(2587): note: Siehe Deklaration von "v8::Object"
..\src\node_pdfium.cc(581): error C2039: "GetIndexedPropertiesExternalArrayDataLength": Ist kein Element von "v8::Object" [C:\Users\rschaar\Documents\Visual Studio 2015\Projects\PdfMakeJS\src\PdfMakeJS\node_m
odules\pdfium\build\node_pdfium.vcxproj]
  c:\users\rschaar.node-gyp\4.4.7\include\node\v8.h(2587): note: Siehe Deklaration von "v8::Object"
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\rschaar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "D:\Program Files\nodejs\node.exe" "C:\Users\rschaar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\rschaar\Documents\Visual Studio 2015\Projects\PdfMakeJS\src\PdfMakeJS\node_modules\pdfium
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\Program Files\nodejs\node.exe" "C:\Users\rschaar\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "--no-bin-link" "pdfium"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pdfium@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdfium@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pdfium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pdfium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pdfium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rschaar\Documents\Visual Studio 2015\Projects\PdfMakeJS\src\PdfMakeJS\npm-debug.log

Sorry to reopen this issues, but i have the same problem. What do you mean about 0.12.10? Is this the version of node-gyp? Which steps do you do to solve your problem?

**Comment by kvlknctk** [comment]
+1

**Comment by guicercal** [comment]
+1
