### ISSUE TITLE
can't build on windows7 32-bit

### ISSUE THREAD

**Issue by dph5199278** [tojocky/node-pdfium-native#3]
I'm a rookie. I try to use 'npm install pdfium' command, but always error.

Info:

2421 info preinstall pdfium@0.0.1
2422 silly install resolved []
2423 verbose about to build C:\Users\xiaoai\node_modules\pdfium
2424 info build C:\Users\xiaoai\node_modules\pdfium
2425 verbose linkStuff [ false, false, false, 'C:\Users\xiaoai\node_modules' ]
2426 info linkStuff pdfium@0.0.1
2427 verbose linkBins pdfium@0.0.1
2428 verbose linkMans pdfium@0.0.1
2429 verbose rebuildBundles pdfium@0.0.1
2430 info install pdfium@0.0.1
2431 verbose unsafe-perm in lifecycle true
2432 info pdfium@0.0.1 Failed to exec install script
2433 verbose unlock done using C:\Users\xiaoai\AppData\Roaming\npm-cache_locks\pdfium-791539a3aa48c796.lock for C:\Users\xiaoai\node_modules\pdfium
2434 verbose stack Error: pdfium@0.0.1 install: `node-gyp rebuild`
2434 verbose stack Exit status 1
2434 verbose stack     at EventEmitter.<anonymous> (D:\Tools\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
2434 verbose stack     at EventEmitter.emit (events.js:110:17)
2434 verbose stack     at ChildProcess.<anonymous> (D:\Tools\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
2434 verbose stack     at ChildProcess.emit (events.js:110:17)
2434 verbose stack     at maybeClose (child_process.js:1008:16)
2434 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
2435 verbose pkgid pdfium@0.0.1
2436 verbose cwd C:\Users\xiaoai
2437 error Windows_NT 6.1.7600
2438 error argv "D:\Tools\nodejs\\node.exe" "D:\Tools\nodejs\node_modules\npm\bin\npm-cli.js" "install" "pdfium"
2439 error node v0.12.1
2440 error npm  v2.5.1
2441 error code ELIFECYCLE
2442 error pdfium@0.0.1 install: `node-gyp rebuild`
2442 error Exit status 1
2443 error Failed at the pdfium@0.0.1 install script 'node-gyp rebuild'.
2443 error This is most likely a problem with the pdfium package,
2443 error not with npm itself.
2443 error Tell the author that this fails on your system:
2443 error     node-gyp rebuild
2443 error You can get their info via:
2443 error     npm owner ls pdfium
2443 error There is likely additional logging output above.
2444 verbose exit [ 1, true ]
2445 verbose unbuild node_modules\pdfium
2446 info preuninstall pdfium@0.0.1
2447 info uninstall pdfium@0.0.1
2448 verbose unbuild rmStuff pdfium@0.0.1 from C:\Users\xiaoai\node_modules
2449 info postuninstall pdfium@0.0.1
2450 verbose gentlyRm vacuuming C:\Users\xiaoai\node_modules\pdfium
2451 silly gentlyRm purging C:\Users\xiaoai\node_modules\pdfium
2452 silly gentlyRm quitting because other entries in C:\Users\xiaoai\node_modules

node-gyp rebuild is failed.what need tools for it?Thank you

**Comment by tojocky** [comment]
sorry for silly question: do you have python 2.7.x installed and configured correctly?

**Comment by dph5199278** [comment]
I have installed python and configured in path env. it use npm install printer command is successful, but  use npm install pdfium command is failed
npm install printer   and    npm install pdfium,are they need the same tools?
is it need V8 JavaScript and ICU?

**Comment by dph5199278** [comment]
Sorry,i think maybe it is build pdfium's question.I don't kwon pdfium is Chromium's open souce.

For build instructions visit https://code.google.com/p/pdfium/wiki/Build

Diff:
- removed v8 folder

this info put tojocky/node-pdfium maybe good for rookie?
